name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      # LuaFormat builds an unneeded test executable. Save time by disabling that.
      BUILD_TESTS: OFF

    steps:
    - uses: actions/checkout@master

    - uses: leafo/gh-actions-lua@v8.0.0
      with:
        luaVersion: "5.4"

    - uses: leafo/gh-actions-luarocks@v4.0.0

    - name: Cache Lua packages
      uses: actions/cache@v2
      with:
        path: ${{ github.workspace }}/.luarocks
        key: lua-${{ hashFiles('atlas-dev-1.rockspec') }}

    - name: set path
      run: echo "${{ github.workspace }}/.luarocks/bin" >> $GITHUB_PATH

    - name: build
      run: make build

    - name: lint
      run: luacheck src tests

    - name: style
      run: "find src tests -name '*.lua' -print0 | xargs -0 lua-format --check"

    - name: test
      run: |
        make coverage
        cat luacov.report.out | grep Total | grep 100.00% > /dev/null
