name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - uses: leafo/gh-actions-lua@v8.0.0
      with:
        luaVersion: "5.4"

    - uses: leafo/gh-actions-luarocks@v4.0.0

    - name: build
      run: |
        luarocks install busted
        luarocks install luacheck
        luarocks install LuaCov
        luarocks build

    - name: lint
      run: |
        luacheck src tests

    - name: test
      run: |
        make coverage
